ordinary_data/08_valve/02_tr_valve_pipe.sql

sql was not working as  02_tr_valve_pipe.sql was encoded as "UTF-8 Unicode (with BOM) text".
When executing the create_schemas, '<feff>' was appearing out of nowhere in the code.
Script used: http://thegreyblog.blogspot.ro/2010/09/shell-script-to-find-and-remove-bom.html
Good morning and all the best.

fix sql script as file was encoded as UTF-8 Unicode (with BOM) text

---

ordinary_data/08_valve/01_od_valve.sql
value_lists/vl_valve_function.sql
value_lists/vl_valve_type.sql

Hello again,
I added the:
- handle_altitude_real
- handle_precision
- handle_precisionalti 
columns for the valve handle in order to avoid a possible problem where users could mistakenly think that the altitude_real, precision and precisionalti columns refer to the handle and not the actual valve-node.
After I get your ok on this will also make a pull for the valve ui. 
Also, I will need to create some check constraints so that in the case the handle_geometry is present --> non-null values in the handle precision columns.
Regarding valve types, I simply added the "gate valve" in the value list + filled english values.
However, I am proposing to also move the shut-off/arrêt and the "vent/jauge" valves from type to function. Thoughts on this?
It's also clear to me that the valves still need …

Valve refactoring take 2

---

ordinary_data/nodes/od_node.sql
ordinary_data/pipe/od_pipe_geom.sql
ordinary_data/surveypoint/od_surveypoint.sql

The triggers that make the 2d to 3d translation don't get to run
due to typemod constraints that are run before the geometry is fixed.
This enables the old behaviour of storing geometry with check constraints.
Followup https://github.com/qwat/qwat-data-model/commit/78e9dd183fae78ec39dbf86a404aad5d727a5e66

fix for new inserts for 3D geometry

---

ordinary_data/installation/od_cover.sql
ordinary_data/nodes/od_node.sql
ordinary_data/pipe/od_crossing.sql
ordinary_data/pipe/od_pipe_geom.sql

Other possible tables that can have NOT NULL but I wasn't sure if there's any usage of these geometry-less wise:
- leak
- printmap
- pressurezone
- protectionzone
- remote
- subscriber_reference
If you think these should always have geometry then I can make the changes and rebase.

geometry NOT NULL constraint for pipes, cover, node, crossings

---

update/delta/delta_1.2.8_schema_visible_perf.sql
update/upgrade_db.sh
update/verify_upgrade_db.sh

So, delta file for 1.2.8 is fixed, as is upgrade_db.sh script for local updates. it works for migration from 1.2.6 to 1.2.8 at least. 
I couldn't find any working configuration to fix the travis script for all possible use cases because of dependencies to generated view in manual views. 
So, as long as this conformity checking script has a few days to live, I will stop wasting time on that old script, unless someone finds a nice solution to that. 
I'll squash commit history before merge.

fixup for 1.2.8

---

init_qwat.sh
system/fn_enable_schemavisible.sql
update/delta/delta_1.2.8_schema_visible_perf.sql

This time, 
changing trigger naming in init process and restore correct naming in delta file. 
Also Rename fn_enable_schemaview.sql to fn_enable_schemavisible.sql and fix init_qwat.sh to use this new name. This will keep naming convention correct. 
The migration works from 1.2.6 on my install up to 1.2.9 using the fixed upgred_db.sh. 
@3nids I'm letting you merge or fix it using another method.

fix 2 for 1.2.8

---

.travis.yml

using 1.2.1 full dump instead of 1.0.0. This will allow the automatic demo data upgrade. 
We don't have many users in production between 1.0.0 and 1.2.1, so that shouldn't be a big issue not to test each time updates from 1.0.0

use a full demo data dump instead of empty Db

---

init_qwat.sh
update/upgrade_db.sh

1. Replace more gnued/linuxism script
1.1. getopt
Using long args with getopt is a linuxism. So I include a "compat mode" for it. More details on [stackoverflow](https://stackoverflow.com/a/7948533/8299570)
1.2. sed
`sed r` is the GNU sed version. Use coreutils with gsed for non linux. Or easiest, use `cat`
1.3. sleep
Use only the number of seconds without the suffix.
2. upgrade_db.sh
2.1. SCRIPTDIR
Add the location of the script. Since you can run it everywhere
2.2. DB info from pg_service.conf
TODO is done. Get the host and the port for dbcomp and dbtest.
Maybe add an option for the location of .pg_service.conf?
Wouldn't it be better if this part were done by PUM?

Fixes init_qwat and upgrade_db.sh

---

ordinary_data/installation/od_cover.sql
ordinary_data/leak/od_leak.sql
ordinary_data/pipe/od_crossing.sql
ordinary_data/surveypoint/od_surveypoint.sql
ordinary_data/valve/od_valve.sql
update/delta/delta_1.3.2_001_missing_spatial_indexes.sql

Missing spatial indexes for some qwat_od's tables:
* cover - geometry
* cover - geometry_polygon
* crossing - geometry
* leak - geometry
* surveypoint - geometry
* valve - handle_geometry

Missing spatial indexes for some qwat_od's tables

---

requirements.txt

The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead.

Update requirements.txt: psycopg2->psycopg2-binary

---

.build/travis_before_script.sh
.build/travis_script.sh
.travis.yml

This WIP at the moment.
Currently the Travis will continue when one of the steps fails in the `script` part. Instead we want the Travis build to stop as soon as something fails. So this PR introduces a `travis_script.sh` script to fix the problem. I also created `travis_before_script.sh` for consistency reasons and to make the code clearer.

Make the Travis build stop on pum errors

---

system/audit.sql
system/audit_tables.sql
system/audit_views.sql
update/delta/delta_1.3.2_004_auditing_functions.sql
update/delta/post-all.sql
update/delta/pre-all.sql

Fixes https://github.com/qwat/QWAT/issues/248.
Depends on #232, which should be merged first.

Deactivate tables auditing during migrations

---

.deploy/create_release.py

This modifies the `create_release.py` script to also create structure-only dumps. Structure-only dumps are useful when one wants to get an empty QWAT database without having to clone the Git repo and run `init_qwat.sh`.
As discussed @lbartoletti will take care of updating the docs to take this setup path into account.

Make Travis create structure-only dumps

---

.deploy/create_release.py

I updated the dump file name on the 1.3.2 release page.

Fix value_list_data_only dump name

---

.build/travis_script.sh

The latest version of Pum ([0.5.11](https://pypi.python.org/pypi/pum/0.5.11)) supports multiple delta directories on the command line (`-d DIR1 DIR2`). We will that for extensions and customizations with their own delta directories.
This PR modifies the Travis script to start exercising this new Pum feature. For now a dummy delta dir (`/tmp/delta`) with a dummy delta files (`SELECT 1;`) are used. When deltas will be added for the SIRE extension we will be able to test with these deltas instead of the dummy one added here.

Exercise Pum's multi delta dir feature in Travis

---

ordinary_data/valve/od_valve.sql
update/delta/delta_1.3.3_003_fix_valve_altitude.sql

Fix https://github.com/qwat/qwat-data-model/issues/187
SRID was missing:
```
ERROR: Geometry SRID (0) does not match column SRID (21781)
État SQL :22023
Contexte : PL/pgSQL function qwat_od.ft_valve_main_altitude() line 16 at assignment
```
And update the logic for insert

Fix #187 valve altitude

---

update/delta/delta_1.3.3_005_add_compteurdechantier_part_type.sql
value_lists/vl_part_type.sql

qwat_vl.part_type: add a new "Compteur de chantier" entry
I'm not sure about the EN translation.
@tudorbarascu is "contor de construcții" corrects for RO translation?
cc @kandre @ponceta

Add 'Compteur de chantier' for part_type and EN/RO translations

---

.build/customizations/sigip/damage/damage.sql
.build/customizations/sigip/init.sh
.build/customizations/sigip/insert_views.sh
.build/customizations/sigip/rewrite_views.sh

This (hopefully) fixes the Travis build errors observed in #271, by properly structuring the sigip customization used in the tests.
Let's see what Travis says.

Fix the sigip customization structure

---

update/upgrade_db.sh

This is an attempt to eliminate the remaining build error:
```
psql:/home/travis/build/qwat/qwat-data-model/roles.sql:3: ERROR:  role "qwat_viewer" cannot be dropped because some objects depend on it
```

Change upgrade_db.sh to avoid re-creating the roles

---

ordinary_data/pipe/od_pipe.sql
update/delta/delta_1.3.3_011_reworked_pipe_year_constraints_and_comments.sql

Reworked constraints on year, year_rehabilitation and year_end columns
constraints so that the values are smaller that the current year.
I also added comments on the constraints and on the columns.
Is there any reason that the year would be bigger than the current_year and smaller than 2100.
I am thinking about having a convention so that pipes that are in a project (with `fk_status` 1306 - which means they are in a project) could have a `year` value that is bigger than the current year and that it should represent the year when the pipe should be installed. I don't know yet if this would serve anyone, but I just thought of bringing it out as a possibility.
I am unsure of my English when describing the year_end column **.. year when the pipe was shut down**. Maybe someone can suggest a …

pipe year columns <= current year + column comments

---

ordinary_data/surveypoint/od_surveypoint.sql
update/delta/delta_1.3.3_014_add_surveypoints_sequence.sql

Follow-up to #185 
It seems alright from my point of view. However, I didn't understood what was the purpose of the ``ALTER TABLE qwat_od.surveypoint ADD COLUMN id integer NOT NULL REFERENCES qwat_od.surveypoint(id) PRIMARY KEY;`` old construct, so there must be something I'm missing.
Thoughts?

Add default sequence to survey points

---

update/delta/post-all.py

For the moment, it is not possible to pass variables to pum. While waiting for an evolution of pum, I propose to get the SRID from the database. This is only one way among many to achieve this workaround. There are others.

Remove hardcored SRS

---

ordinary_data/views/schematic/vw_pipe_schema.sql

A bracket closed wrongly the union / linemerge expression, and it only failed on some real data situations (with non connected pipes)
A simple fix so

fixes wrong bracket closure on schematics

---

update/delta/delta_1.4.0_003_create_fk_leak_type.sql
value_lists/vl_leak_type.sql

Fix delta constraint around leak types

Fix delta constraint around leak types

---

.build/customizations/sigip/views/damage.sql
.build/customizations/sigip/views/hydrant.sql
.build/customizations/sigip/views/installation.sql
.build/customizations/sigip/views/leak.sql
.build/customizations/sigip/views/part.sql

Example of how export views should look like VS reference to productions views like vw_element_hydrant

Avoid references to productions views directly (prefer tables)

---

tests/test_scenarii_scalability.model

Fix an error when running scalability tests because new field type for `fk_distributor` has not been updated in PR https://github.com/qwat/qwat-data-model/pull/359 as it was the case in commit https://github.com/qwat/qwat-data-model/pull/359/commits/904b154b64d75eba5ac69af1c28b73310af0632d for other tests.
See comment https://github.com/qwat/qwat-data-model/pull/345#issuecomment-1386995958

Update scalability tests with new field type (fk_distributor)
