value_lists/vl_installation_type.sql
value_lists/vl_part_type.sql

added fittings parts

---

ordinary_data/06_hydrant/0_od_hydrant.sql
system/audit_tables.sql
value_lists/readme
value_lists/vl_hydrant_material.sql

For increased consistency, Do you think we should move the hydrant_provider values to start with 71 let's say?

added hydrant materials

---

ordinary_data/06_hydrant/0_od_hydrant.sql
ordinary_data/07_pipe/0_od_pipe.sql
ordinary_data/08_valve/01_od_valve.sql
ordinary_data/10_installation/0_od_installation_building.sql
value_lists/readme
value_lists/vl_locationtype.sql
value_lists/vl_valve_actuation.sql

Do you want me to add a locationtype to the ui's ?
All the best,
Tudor

added location type as discussed in https://github.com/qwat/qwat-data-model/issues/36

---

ordinary_data/installation/od_installation_building.sql
ordinary_data/installation/od_installation_chamber.sql

Hi,
Is there a reason why we don't have remark & altitude columns for installation building?
ping @3nids

Add remark + altitude to installation building

---

ordinary_data/pipe/od_pipe.sql

Fixes https://github.com/qwat/QWAT/issues/49

Rework obsolote comment on pipes.

---

ordinary_data/demo.sql
ordinary_data/noedit_views/vw_valve_lines.sql
ordinary_data/valve/od_valve.sql
value_lists/vl_part_type.sql

node_altitude values should go into altitude when migrating

Fixed valve with handle view/demo distributor/removed node_altitude

---

ordinary_data/installation/od_installation_chamber.sql
ordinary_data/nodes/od_node.sql
value_lists/vl_part_type.sql
value_lists/vl_pipe_material.sql
value_lists/vl_subscriber_type.sql
value_lists/vl_valve_function.sql

add manometer to installation parts and installation chamber (boolean)
add check constraint to verify if altitude precision is selected when altitude present

add manometer, add fk_precisionalti check when altitude non null

---

ordinary_data/installation/od_cover.sql

See https://github.com/qwat/qwat-data-model/issues/80

cover diameter -> form_dimension & added polygon geom & fixed geom inserts

---

ordinary_data/nodes/fn_node_create.sql
ordinary_data/pipe/od_pipe_geom.sql
tests/test_add_node.expected.sql
tests/test_add_node.sql

@3nids is it this kind of change you had in mind ?

Disable the creation of pipe vertex when doing a pipe creation

---

init_qwat.sh
system/versions.sql
system/versions_insert.sql

I chose to store a varchar version following semver, and provide a function to extract version parts.

Add a table to store qWAT versions. Store model version.

---

value_lists/vl_pipe_material.sql

improve comments on pipe material diameter columns

---

drawing/constructionpoint.sql

Fix https://github.com/qwat/qwat-data-model/issues/116

Add 3d to construction points

---

update/verify_upgrade_db.sh

One travis build has failed so proposing one option to avoid such errors

add --if-exists option to avoid failure if db was not already there

---

ordinary_data/views/inheritance/od_all_inheritance.py
ordinary_data/views/insert_views.sh
update/delta/delta_1.1.0.sql
update/delta/delta_1.2.0.sql

Building trigger in one shot (no more hierarchy)

---

update/upgrade_db.README

Add debuging hints to ease the update process.

Add debuging hints

---

.travis.yml
update/delta/delta_1.3.0_upgrades_table.sql

Set pum integration "entry point" to db version 1.3.0

Pum integration

---

.deploy/create_release.py
.gitmodules
.travis.yml
ordinary_data/views/export/export_hydrant.py
ordinary_data/views/export/export_installation.py
ordinary_data/views/export/export_leak.py
ordinary_data/views/export/export_meter.py
ordinary_data/views/export/export_part.py
ordinary_data/views/export/export_pipe.py
ordinary_data/views/export/export_printmap.py
ordinary_data/views/export/export_remote.py
ordinary_data/views/export/export_subscriber.py
ordinary_data/views/export/export_valve.py
ordinary_data/views/export/sql_export_view.py
ordinary_data/views/inheritance/od_all_inheritance.py
requirements.txt
tests/test_scalability.py
tests/test_scalability_multithread.py
update/test_migration.py

A.k.a. "continuous deployment"
* Deployment happens only if all tests including pum succeed
* Deployment uploads to a new release
* The release name is the name of the current git tag
* Four dumps are uploaded (sql and custom)
* Travis output has been cleaned up
Pum is now installed using pip from pypi, the submodule has been removed.
This should only be merged, once we have a clean migration path with a green travis.
You can find a sample on what the new download page looks like here: https://github.com/m-kuhn/qwat-data-model/releases/tag/9.9

Deploy demodata automatically from travis

---

ordinary_data/functions/rewrite_functions.sh
ordinary_data/views/export/export_hydrant.py
ordinary_data/views/export/export_installation.py
ordinary_data/views/export/export_leak.py
ordinary_data/views/export/export_meter.py
ordinary_data/views/export/export_part.py
ordinary_data/views/export/export_pipe.py
ordinary_data/views/export/export_printmap.py
ordinary_data/views/export/export_remote.py
ordinary_data/views/export/export_subscriber.py
ordinary_data/views/export/export_valve.py
ordinary_data/views/export/sql_export_view.py
ordinary_data/views/inheritance/od_all_inheritance.py
tests/test_scalability.py
tests/test_scalability_multithread.py
tests/tests.sh
tests/tests_scalability.sh
tests/tests_scalability_multithread.sh
tools/srid_21781_to_2056.sh
update/upgrade_db.sh

Like https://github.com/qgis/QGIS/pull/6229
Todo:
[x] Tests python2/python3?
[x] Clean old python stuff?
[x] Pep8

Standardize shebangs

---

system/audit_views.sql

More explicit:
```
-<U+FEFF>/* Audit views only for those having explicit triggers handling data editing*/
+/* Audit views only for those having explicit triggers handling data editing*/
```

Fixes invalid char in system/audit_views.sql

---

init_qwat.sh

Don't hardcode version in init_qwat.sh

Numversion init qwat

---

update/delta/delta_1.3.2_1_add_more_pipe_protection_values.sql
value_lists/vl_pipe_protection.sql

For PE and Steel pipes there were only OLD pipes selection but we have heavy traffic pipes that are protected with New pipes (PE, Steel or PVC).
Thoughts?

Pipe protection

---

extensions/ch_vd_sire/insert_views.sh
init_qwat.sh
ordinary_data/functions/rewrite_functions.sh
ordinary_data/views/insert_views.sh
ordinary_data/views/rewrite_views.sh
tests/test_scalability.py
tests/test_scalability_multithread.py
tests/tests.sh
tests/tests_scalability.sh
tests/tests_scalability_multithread.sh

A service is required and it's explicit with this command.
This adds security in case when the service is not found/exported. (I found one case, that I need to investigate).

Add service arg everywhere

---

init_qwat.sh
requirements.txt

Fix https://github.com/qwat/QWAT/issues/275

Use pum 0.5.13 for compatibility. Since new versions breaks our scripts.

---

README.md

Add the complete changelog link (accessible through the releases)
https://github.com/qwat/qwat-data-model/releases/tag/1.3.2

Update Changelog according to 1.3.2

---

requirements.txt

pum==0.6.7
Since https://github.com/opengisch/pum/commit/15d962dbcc551b929769c0fb742ece10556bb1d6

Update pum to latest version

---

.build/customizations/sigip/damage/damage.sql
.build/customizations/sigip/delta/post-all.py
.build/customizations/sigip/delta/pre-all.py
.build/customizations/sigip/drop_views.sql
.build/customizations/sigip/init_sigip.sh
.build/customizations/sigip/inserts.sh
.build/customizations/sigip/rewrite_views.sh
.build/customizations/sigip/views/damage.sql
.build/customizations/sigip/views/hydrant.sql
.build/customizations/sigip/views/installation.sql
.build/customizations/sigip/views/leak.sql
.build/customizations/sigip/views/part.sql
.build/customizations/sigip/views/pipe.sql
.build/customizations/sigip/views/valve.sql
.build/travis_script.sh
update/upgrade_db.sh

This PR adds the ability to use customization.
The test with travis is an example for that.

Customization

---

update/delta/delta_1.3.3_004_add_J_short_fr_jauge_valve_function.sql
value_lists/vl_valve_function.sql

qwat_vl.valve_function: add for vent valve the J value for the short_fr attribute, as it is the case for other
cc @kandre

add 'J' short_fr for Jauge in valve_function

---

.build/customizations/sigip/damage/damage.sql

see https://github.com/qwat/qwat-data-model/pull/271#issuecomment-423189381

Add 'IF NOT EXISTS' to qwat_od.damage

---

.build/travis_script.sh

only views and rules where tested up to now

enforce PUM checks to all possible checks

---

ordinary_data/installation/od_cover.sql
update/delta/delta_1.3.3_010_add_cover_fk_precision_alti_fk_obj_reference.sql

See #80 
I'll make the delta file after the CI is working again.

add fk_precision, fk_precisionalti and fk_object_reference to cover

---

ordinary_data/hydrant/od_hydrant.sql
update/delta/delta_1.3.3_013_allow_single_part_underground_hydrants.sql

Enables underground hydrants to only have one part

---

ordinary_data/installation/od_cover.sql
update/delta/delta_1.3.3_015_add_fk_protection_somo_comments.sql
value_lists/vl_pipe_protection.sql

Describe what fk_protection SOMO value stands for

---

ordinary_data/surveypoint/od_surveypoint.sql
update/delta/delta_1.3.3_017_add_depth_to_surveypoints.sql

Add depth information to surveypoints according to 
https://github.com/qwat/qwat-data-model/issues/139

Add depth information to surveypoints

---

init_qwat.sh
update/upgrade_db.sh

Remove pum baseline on qwat_comp (upgrade)

---

.build/customizations/sigip/drop.sh

Drops the schema with the views and drops the table qwat_od.dammage
cc @ponceta

Adds script to drop the customizations

---

ordinary_data/views/export/export_meter.py

Fix https://github.com/qwat/qwat-data-model/issues/288

Fix wrong foreign key on export meter view

---

update/delta/delta_1.3.3_010_add_cover_fk_precision_alti_fk_obj_reference.sql

Follow-up to #188
@ponceta I think this should cover the small issue, right?

Set fk_object_reference and fk_precisionalti "TO BE DETERMINED" for covers with existing altitude

---

.build/travis_script.sh
.travis.yml

Reverts qwat/qwat-data-model#276
-i stands for ignore, PUM is not checking anything anymore here.

Revert "enforce PUM checks to all possible checks"

---

update/delta/delta_1.3.4_000_be_specific_about_surveying_altitude.sql
value_lists/vl_object_reference.sql

fixes https://github.com/qwat/QWAT/issues/290

be specific about altitude object reference regarding pipes

---

.gitmodules
ordinary_data/views/inheritance/od_all_inheritance.py
ordinary_data/views/inheritance/pg_inheritance_view_recursive.py

Since there is only one script used in metaproject repository and by QWAT only, we think it's better to have it placed here and to archive the repository.
discussed with @ponceta

Archive metaproject submodule

---

ordinary_data/views/export/export_hydrant.py
ordinary_data/views/export/export_installation.py
ordinary_data/views/export/export_leak.py
ordinary_data/views/export/export_meter.py
ordinary_data/views/export/export_part.py
ordinary_data/views/export/export_pipe.py
ordinary_data/views/export/export_printmap.py
ordinary_data/views/export/export_remote.py
ordinary_data/views/export/export_subscriber.py
ordinary_data/views/export/export_valve.py
ordinary_data/views/inheritance/pg_inheritance_view_recursive.py

Remove the deprecated yaml.load method
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Fix yaml warnings

---

README.md

Update Readme to 1.3.5

---

README.md

Add v 1.3.6 release in changelog

Add v 1.3.6 release in changelog

---

update/upgrade_db.sh

Test default directory for delta folder

---

ordinary_data/views/export/export_pipe.py

Export pipe srid

---

.build/customizations/sigip/views/hydrant.sql
.build/customizations/sigip/views/installation.sql
.build/customizations/sigip/views/part.sql

Fix rebase issue

---

update/upgrade_db.sh

Fix for upgrading production database by manually doing it with pum because audit triggers are not in 1.3.6 dump, but it is present in initialisation script.

Fix upgrade database with audit triggers

---

ordinary_data/pipe/od_pipe.sql
update/delta/delta_1.4.1_002_remove_default_pn_for_pipes.sql

Related to https://github.com/qwat/qwat-data-model/issues/107#issuecomment-437679392
Need some hint on the failing test.

Do not use an arbitrary default value for PN

---

.github/workflows/run_tests.yml

Adapt test matrix to latest-1, latest and future

Adapt test matrix to latest-1, latest and future

---

datamodel/.docker/Dockerfile
docker-compose.yml

Upgrade pg versions according to roadmap

Upgrade pg versions according to roadmap
